lib/ui/animated_qr_image.dart, lib/ui/pages/scv/scv_scan_qr.dart, lib/ui/pages/scv/scv_show_qr.dart, pubspec.lock, pubspec.yaml
...so it doesn't animate in background
=> ENV-216: remove ScvShowQrPage off onboarding navigation stack

ios/Flutter/AppFrameworkInfo.plist, ios/Podfile.lock, ios/Runner/Info.plist, lib/ui/home/cards/accounts/account_card.dart, lib/ui/home/cards/accounts/accounts_card.dart, lib/ui/home/cards/accounts/confirmation_card.dart, packages/wallet/native/wallet-ffi/Cargo.toml, packages/wallet/native/wallet-ffi/src/lib.rs, pubspec.yaml
https://twitter.com/bitcoindevkit/status/1588266599030611970
=> ENV-263: update BDK

build_ffi_android.sh
=> ffi: use specific Rust version

Dockerfile
Automatically updates via apt and installs minimal dependencies w/ clearing of cache directories after apt dependency installation.
=> Minor space optimizations for Dockerfile

build_ffi.sh, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, macos/Runner/DebugProfile.entitlements
=> Fix macOS build

android/app/src/main/kotlin/com/foundationdevices/envoy/MainActivity.kt, lib/business/fw_uploader.dart, lib/ui/onboard/sd_card_spinner.dart, lib/ui/pages/fw/fw_microsd.dart, lib/ui/pages/fw/fw_progress.dart
* removed timer and added event based for progress state
* added SDcard write failure message and progress state
* re-wired riverpod implementation
=> Improved SDcard fw writing progress

lib/ui/home/cards/accounts/accounts_card.dart, lib/ui/home/cards/accounts/accounts_list_fade_edge_shader.dart, lib/ui/home/home_page.dart, lib/ui/onboard/magic/wallet_security/wallet_security_modal.dart, lib/ui/onboard/manual/manual_setup_import_backup.dart
- SFT-1577: fix backup menu crash
- SFT-1567: fix android back button
- SFT-1543 : fade edge effect for accounts card
- SFT-1539: fix CTA button alignment
=> Hw UI fixes

lib/ui/home/home_page.dart, lib/ui/onboard/magic/magic_recover_wallet.dart, lib/ui/onboard/manual/generate_seed.dart, lib/ui/onboard/wallet_setup_success.dart, lib/ui/widgets/toast/envoy_toast.dart
[SFT-1602 : missing close icon](https://github.com/Foundation-Devices/envoy/commit/17149e10263ceb55e4550853ba0bc15863313c68)
[SFT-1649: seed grid button cut off fix](https://github.com/Foundation-Devices/envoy/commit/6d1ed1c10d1db4e7881ff4bc189e677fd520697d)
[SFT-1600: Fix toast stacking](https://github.com/Foundation-Devices/envoy/commit/80be387a4fb67325cdc9259dd256caaab934149c)
[SFT-1514: fix missing text](https://github.com/Foundation-Devices/envoy/commit/4dd576ad7b03703ae34f73029163c3e8aad96ec1)
=> UI bug fixes

lib/business/account.dart, lib/business/account.g.dart, lib/business/account_manager.dart, lib/ui/home/cards/accounts/account_card.dart, lib/ui/state/hide_balance_state.dart
*Fixed : Hiding wallet value doesn't hide transaction value
=> Accounts UUID and hide amount revamp

ios/Podfile.lock, lib/business/envoy_seed.dart, lib/business/feed_manager.dart, lib/main.dart, lib/util/envoy_storage.dart, test/restore_test.dart
FeedManager was doing blocking operations. EnvoySeed didn't perform a migration step for older backups.
=> Fix FeedManager and EnvoySeed

lib/ui/home/home_page.dart
if the user is in any of other tabs ( devices, activity etc..) the android back button navigate back to accounts home
=> Fix back press to navigate back to accounts home

lib/ui/home/cards/accounts/accounts_card.dart, lib/ui/home/cards/accounts/detail/coins/warning_dialogs.dart, lib/ui/home/cards/accounts/detail/filter_state.dart
also includes ENV-39 : reminder flag not storing
=> Fix persistent account details filters

lib/ui/home/cards/accounts/detail/coins/coin_balance_widget.dart, lib/ui/home/cards/accounts/detail/coins/coin_details_widget.dart, lib/ui/home/cards/accounts/detail/coins/coin_tag_details_screen.dart, lib/ui/home/cards/accounts/detail/coins/warning_dialogs.dart
1. Env 157 reset sorting works too early
2. ENV-370-warning-not-overlapping-menu
=> Env 157 reset sorting works too early

lib/ui/home/cards/accounts/accounts_card.dart, lib/ui/home/cards/activity/activity_card.dart, lib/ui/home/cards/devices/devices_card.dart, lib/ui/home/cards/privacy/privacy_card.dart
Make fade on all screens smaller, better-looking and consistent
=> Fix fade on home page screens

lib/ui/home/cards/accounts/detail/coins/coin_tag_details_screen.dart, lib/ui/home/cards/accounts/spend/psbt_card.dart, lib/ui/home/cards/accounts/spend/tx_review.dart, lib/ui/routes/accounts_router.dart
* fix for immediate broadcast after passport sign 
* added warning dialog before leaving review screen
* fix scroller bug when opening coin tag
=> ENV 321 passport transaction is automatically broadcast after

lib/business/notifications.dart
This happens when we transfer between our accounts
=> ENV-354: add notification with same txid but different amount

lib/business/envoy_seed.dart
Updated wording on seed message
=> ENV-471: update wording on seed message

lib/business/envoy_seed.dart, lib/business/settings.dart
Instead respect user choice during onboarding
=> ENV-133: don't restore Tor preference

lib/business/notifications.dart
=> ENV-476: migrate old account-less tx notifications

lib/ui/home/cards/accounts/spend/fee_slider.dart, lib/ui/home/cards/accounts/spend/spend_state.dart
=> ENV-488: workaround max fee sometimes too high

lib/ui/animated_qr_image.dart, lib/ui/home/cards/accounts/address_card.dart, lib/ui/home/cards/accounts/descriptor_card.dart, lib/ui/home/settings/backup/export_seed_modal_qr_code.dart, lib/ui/onboard/onboarding_page.dart, lib/ui/widgets/envoy_qr_widget.dart, pubspec.lock, pubspec.yaml
=> ENV 540 - Updated QR widget 

lib/business/connectivity_manager.dart, lib/business/exchange_rate.dart, lib/main.dart, packages/backup/pubspec.yaml, packages/http_tor/pubspec.yaml, pubspec.lock, pubspec.yaml
- Bumped to latest version
- Smarter FX rate fetching on Tor
- Smarter connectivity notifications
- `nofile_limit` bump to avoid OS error 21 (too many open files) - especially on iOS
=> Tor improvements

lib/business/account_manager.dart, lib/ui/pages/scanner_page.dart
Just in case user wants to verify an address again
=> ENV-764: pass an existing wallet back to scanner in case account already paired

lib/ui/home/cards/accounts/spend/rbf/rbf_button.dart
The dimensions are not precisely identical; an average of currently accessible languages has been used.
=> ENV-798: ensure consistent button size during loading.

lib/business/settings.dart, lib/ui/address_entry.dart, lib/ui/amount_entry.dart, lib/ui/home/cards/accounts/spend/rbf/rbf_spend_screen.dart, lib/ui/widgets/envoy_amount_widget.dart
This reverts commit a9ef3435c373685ec7cbea97e3eed8dd2440316e.
=> Revert "Add flutter_lints and run dart fix"

.github/workflows/android.yml, .github/workflows/ios.yml, justfile, lib/business/map_data.dart, lib/ui/components/map_widget.dart, lib/ui/components/ramp_widget.dart
=> Add API keys to build

lib/ui/home/cards/accounts/detail/coins/coin_tag_details_screen.dart, lib/ui/home/cards/accounts/detail/coins/coins_switch.dart, lib/ui/home/cards/accounts/spend/choose_coins_widget.dart, lib/ui/home/cards/accounts/spend/coin_selection_overlay.dart, lib/ui/home/cards/accounts/spend/rbf/rbf_spend_screen.dart, lib/ui/home/cards/accounts/spend/tx_review.dart, lib/ui/home/home_page.dart, lib/ui/home/top_bar_home.dart
* Removed all global functions to show/hide spend overlays.
* Use wrapper widget to handle provider listeners.
* Implemented hide and show methods in wrapper widget to easily access from child widgets.
=> Improved coin selection overlay implementation

ios/Runner/Base.lproj/LaunchScreen.storyboard
=> Fix IOS launch-screen background color 

lib/business/account_manager.dart, lib/ui/home/home_page.dart
=> ENV-1094: reduce server unreachable toasts
